//get Images
export const REQUEST_GET_IMAGES = 'REQUEST_GET_IMAGES';
export const REQUEST_GET_IMAGES_SUCCESS = 'REQUEST_GET_IMAGES_SUCCESS';
export const REQUEST_GET_IMAGES_FAIL = 'REQUEST_GET_IMAGES_FAIL'
